### ISSUE TITLE
Tries to sync to the wrong notebook

### ISSUE THREAD

**Issue by brett-castellanos** [untitled-ai/jupyter_ascending#10]
First, thanks for this package. It basically exactly what I have been looking for when it comes to editing notebooks.

Second, I am hitting a problem when working with more than one notebook.

`2020-12-15T09:24:24.114108-0800 - Unabled to find /Users/brett/notebooks/notebook2.synced.py in {'/Users/brett/closedloopai/notebooks/notebook1.synced.ipynb': 56389}`

This occurs after I have worked with notebook1 using Jupyter Ascending, and then attempt to work on a second notebook. Closing the old notebook does not help, but restarting the server works.

I am using the following versions:

python: 3.6.12
jupyter core     : 4.7.0
jupyter-notebook : 6.1.5
qtconsole        : 5.0.1
ipython          : 7.15.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.9
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 4.3.3

Please let me know if you need any further information.

**Comment by zplizzi** [comment]
Hey! Sorry to not respond to this. We've done a lot of work on `jupyter_ascending` and pushed several updates, so I'm going to close this in hopes that it has been fixed :) Feel free to reopen if not!
