### ISSUE TITLE
Not syncing automatically

### ISSUE THREAD

**Issue by argapost** [untitled-ai/jupyter_ascending#11]
Hi, thanks for this extension really useful.

I think I have installed it successfully since in the nbextension and serverextension list I see the jupyter_ascending.
```
jupyter serverextension list                                                                                                                                at 11:20:42
config dir: /home/argyris/.jupyter
    jupyter_ascending  enabled 
    - Validating...
      jupyter_ascending 0.1.18 OK
    jupytext  enabled 
    - Validating...
      jupytext 1.8.2 OK
```

I open the console of the jupyter notebook everything seems correct:

```
===================================
extension.js:197 Loading Jupyter Ascending extension...
extension.js:198 Opening...  test.sync.ipynb
extension.js:199 Is synced:  true
extension.js:201 Attemping create comm...
extension.js:221 ... success!
```

When I open in nvim the test.sync.py (produced from your make pair script) and make changes, the changes are not syncing back to my test.sync.ipynb.

If I manually do:
``` bash
python jupyter_ascending/requests/sync.py --filename test.sync.py
```
Then it works.

Same for execution, i have the nvim plugin jupyter_ascending if press space-space-x nothing happens if I call the script 

``` bash
python jupyter_ascending/requests/execute_all.py --filename test.sync.py
```
it works.

Python 3.9.1 but same problem with 3.8.6

Do you have any ideas about what it might be wrong? 

Thank you in advance.

Argyris

**Comment by Lap1n** [comment]
I have the same problem.

**Comment by richban** [comment]
Same here. @Lap1n  @argapost have you guys figure it out?

**Comment by richban** [comment]
@tjdevries perhaps some thoughts? Thanks

**Comment by richban** [comment]
Found the [issue](https://github.com/untitled-ai/jupyter_ascending.vim/blob/5732862740b282c81277e5f95d1fb9d15f5682bd/plugin/jupyter_ascending.vim#L2): 

`let g:jupyter_ascending_match_pattern     = get(g:, 'jupyter_ascending_match_pattern', '.synced.py')`

The vim pluggin only matches this pattern: `synced` and also in the Python module https://github.com/untitled-ai/jupyter_ascending/blob/dc15293a3744e01379fd7ac50f09449773382e20/jupyter_ascending/_environment.py#L16 is inconsistent.

Change the file names to `synced` and als othe `SYNC_EXTENSION = "synced"` and you're good to go.

**Comment by joshalbrecht** [comment]
Yes--I think we did that and merged a patch a few weeks ago, so hopefully this is already fixed!

**Comment by richban** [comment]
Yes it's been merged so should be all good.

**Comment by tfriedel** [comment]
I do get an updated .ipynb file when saving my .py file in vim, but I still have to manually the jupyter notebook. Also the execute shortcuts don't have any effect.

**Comment by richban** [comment]
Check whether other command does not  override the jupyter_ascending commands

```
---- JUPYTER ASCENDING --------------------------------------------------------

vim.cmd[[ nnoremap <silent><c-x> <Plug>JupyterExecute ]]
vim.cmd[[ nnoremap <silent><c-X> <Plug>JupyterExecuteAll ]]
```

**Comment by zplizzi** [comment]
I'm going to go ahead and close this since it seems like things may be working now - feel free to reopen or open a new issue if y'all have any trouble! Also do try the newer version of `jupyter_ascending`, it may fix some issues you may have been having.
