### ISSUE TITLE
Can sync filename without requring ending with .sync

### ISSUE THREAD

**Issue by vpeopleonatank** [untitled-ai/jupyter_ascending#12]
I think It 's more flexible when having no requirement about filename ending extension. Is there any technical issue about filename ending with `.sync.`?

**Comment by Yevgnen** [comment]
Same question here.

**Comment by phcerdan** [comment]
I would love to use this plugin but wondering if I can work without `.sync.` suffixes? @zplizzi might help answering this? Thanks!
