### ISSUE TITLE
Cell index off by one when calling execute()

### ISSUE THREAD

**Issue by rajatvd** [untitled-ai/jupyter_ascending#28]
https://github.com/untitled-ai/jupyter_ascending/blob/ab7ecec2654872726be1ebfa94900dc6745a7224/jupyter_ascending/requests/execute.py#L20-L26

I believe this ignores the case where jupytext has a large multi-line prefix at the start of the file followed by a `# %%` line so this causes the `execute()` command to execute one cell after the actual cell. 

For example, this is the start of the python file:

```
# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:hydrogen
#     text_representation:
#       extension: .py
#       format_name: hydrogen
#       format_version: '1.3'
#       jupytext_version: 1.13.0
#   kernelspec:
#     display_name: Python 
#     language: python
#     name: py
# ---

# %% 
import numpy as np

```

While the first cell of the notebook contains the import numpy statement.

**Comment by Yevgnen** [comment]
Also is `light` format of `jupytext` currently supported?

**Comment by austinliuigi** [comment]
@zplizzi Any chance of merging this in?
