### ISSUE TITLE
Broken link to OTHER_EDITORS.md in README.md

### ISSUE THREAD

**Issue by renzmann** [untitled-ai/jupyter_ascending#41]
I believe this link:
https://github.com/untitled-ai/jupyter_ascending/blob/ab7ecec2654872726be1ebfa94900dc6745a7224/README.md?plain=1#L65

Should be 
```md
- [Other editors](docs/OTHER_EDITORS.md)
```

**Comment by zplizzi** [comment]
Fixed, thanks!
