### ISSUE TITLE
No registered notebook

### ISSUE THREAD

**Issue by ferdinandyb** [untitled-ai/jupyter_ascending#44]
```
2022-10-26T15:07:18.659992+0200 - Finding server for notebook_str, script_path: /home/fbence/Codes/example.sync.ipynb
2022-10-26T15:07:18.660125+0200 - Unable to find a paired notebook for /home/fbence/Codes/example.sync.py in registered notebooks: {}.
Either a properly named notebook (ending in .sync.ipynb) is not running, or it didn't register properly for some reason.
```

I was following the example along and I'm getting this error although the notebook is _definitely_ running. I'm on python 3.9. Any pointers? Thanks!

**Comment by zplizzi** [comment]
Hmm, that should be working - are you sure you followed the installation exactly? What's the output of 
```
$ jupyter nbextension     list
$ jupyter serverextension list
```

**Comment by ferdinandyb** [comment]
Thanks for reaching out! I _think_ I did? Maybe it doesn't like to be in a virtualenv?

```
❯ PYENV_VERSION=jupyter jupyter serverextension list
config dir: /home/fbence/.jupyter
    jupyter_tabnine  enabled
    - Validating...
Error loading server extension jupyter_tabnine
      X is jupyter_tabnine importable?
    jupyter_nbextensions_configurator  enabled
    - Validating...
Error loading server extension jupyter_nbextensions_configurator
      X is jupyter_nbextensions_configurator importable?
config dir: /home/fbence/.pyenv/versions/jupyter/etc/jupyter
    jupytext  enabled
    - Validating...
      jupytext 1.14.1 OK
    jupyter_ascending  enabled
    - Validating...
      jupyter_ascending 0.1.23 OK
❯ PYENV_VERSION=jupyter jupyter nbextension list
Known nbextensions:
  config dir: /home/fbence/.jupyter/nbconfig
    notebook section
      jupyter_tabnine/main disabled
      nbextensions_configurator/config_menu/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main  enabled
      - Validating: OK
      hide_input/main  enabled
      - Validating: OK
      hide_input_all/main  enabled
      - Validating: OK
      toc2/main disabled
      spellchecker/main  enabled
      - Validating: OK
      jupytext/index  enabled
      - Validating: OK
    tree section
      nbextensions_configurator/tree_tab/main  enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
  config dir: /home/fbence/.pyenv/versions/jupyter/etc/jupyter/nbconfig
    notebook section
      jupytext/index  enabled
      - Validating: OK
      jupyter-js-widgets/extension  enabled
      - Validating: OK
      jupyter_ascending/extension  enabled
      - Validating: OK
  config dir: /etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
```

**Comment by zplizzi** [comment]
Hmm, I'm not sure what the problem might be, sorry! Let us know if you figure it out. You do have some warnings/errors in that output, I wonder if those are related somehow.

**Comment by ferdinandyb** [comment]
Can I get the plugins to provide more debug info? I'm guessing the notebook part should try and run some code to register itself with the server, is it possible to get error message from there or to see if it even tried to do so?

**Comment by zplizzi** [comment]
You should see output like this in the jupyter notebook logs: 
```
% jupyter notebook
Logging Jupyter Ascending logs to /var/folders/k5/5485r0sj18vbkvttgzy37rkh0000gn/T/jupyter_ascending/log.log
[I 12:43:52.255 NotebookApp] LOADING JUPYTER ASCENDING SERVER PLUGIN
...
```

If not, there's something messed up with how you've registered the server plugin.

**Comment by ferdinandyb** [comment]
Ok, so the "loading" part shows up alright. Something else is going wrong. I just tried this out in a docker container and works nicely, so my assumption is that I have some obscure setting interfering.

**Comment by ferdinandyb** [comment]
I can't tell what the issue was, but I purged all traces of jupyter and reinstalled and now it's good. Thanks!

**Comment by ferdinandyb** [comment]
Or I may have not properly understood the README: `jupyter` and `jupyter_ascending` need to be installed into the same kernel I'm trying to run the notebook with? I.e. I essentially have to install both into every virtualenv and make sure to run jupyter from the virtualenv? (I'm getting the error again now when I tried to switch kernels).

**Comment by zplizzi** [comment]
I don't think it matters which environment you run `jupyter` from, but yes `jupyter_ascending` needs to be installed in each kernel you want to use with `jupter_ascending`. Pretty sure that's right.

**Comment by ferdinandyb** [comment]
Thanks, I think I have it figured out now, most likely my problem was having half a decade of python versions dragged along several laptops and OS versions with a lot of confused paths, so I ended up not only purging jupyter but basically everything related to python other than the system python and it seems starting from scratch solved the issue :D Thanks very much for the help!
