### ISSUE TITLE
Is there any use case where this is beneficial beyond vs code Jupyter extensions?

### ISSUE THREAD

**Issue by rosmur** [untitled-ai/jupyter_ascending#59]

**Comment by micimize** [comment]
I personally use `vscode-jupyter`, but would say there are pros and cons to each. For example, [some of the issues I've encountered with `vscode-jupyter`](https://github.com/search?q=repo%3Amicrosoft%2Fvscode-jupyter%20author%3Amicimize&type=issues)  probably don't apply to with pure jupyter, and I wouldn't be surprised if there are other widget rendering issues with vscode when dealing with more non-standard/bespoke widgets.

One might also want the stateful `ipynb` artifact of their session (not sure if this is doable with vscode), or just prefer to have things decoupled from the IDE. I personally have a very vscode-centric setup so I prefer just using the vscode extension.
