### ISSUE TITLE
Question: Can this be used with existing jupyter notebooks?

### ISSUE THREAD

**Issue by Duncan-Britt** [untitled-ai/jupyter_ascending#65]
Hi there. This project is awesome!

I understand the workflow of using `python -m jupyter_ascending.scripts.make_pair --base <fname>` to create a pair of synced jupyter files, and then starting the jupyter notebook. But I'm wondering, if I have a long notebook.ipynb file, is there a script to turn that into compatible .sync.py file? Thanks.

**Comment by juanolon** [comment]
hey!
yes, you can use:
```
jupytext --to py:percent <file_name>
```
and then add the .sync suffix to both files

**Comment by Duncan-Britt** [comment]
Thanks!
